---
name: Static Analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: Static Analysis

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version: [8.2, 8.3]
        composer-stability: [prefer-lowest, prefer-stable]
        operating-system:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: Install Dependencies
        run: >-
          composer update
          --${{ matrix.composer-stability }}
          --prefer-dist
          --no-interaction
          --no-progress

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse
